

spring:
  liquibase:
    enabled: false

  datasource:
    username: root
    password: 190407011
    url: jdbc:mysql://localhost:3306/karvan
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  security:
    user:
      password: password
      name: user


server:
  port: 8082


admin:
  email: admin@gmail.com
logging:
  level:
    root: warn


