package com.karvan.entity.karavan;

public enum KaravanAvadanliq {
    KONDISONER, QIZDIRICI, TELEVIZOR, DVD_PLAYER, AVTOMOBIL_RADIOSU, TEMIZLIK_LEVAZIMATLARI,
    MEISET_ESYALARI, SOBA, SOYUDUCU, METBEX_ESYALARI, DAXILI_MASA, YEMEK_UCUN_OTURACAQLAR, YEMEK_DESTI,
    QAZ, DAXILI_DUS, WC, MANQAL_SAMOVAR
}
